-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sigcd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sigcd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sigcd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sigcd` ;

-- -----------------------------------------------------
-- Table `sigcd`.`t_ayuda_temporal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcd`.`t_ayuda_temporal` (
  `ID_AYUDA_TEMPORAL` INT NOT NULL,
  `CEDULA_SOLICITANTE` VARCHAR(45) NOT NULL,
  `NOMBRE_SOLICITANTE` VARCHAR(45) NOT NULL,
  `APELLIDO1_SOLICITANTE` VARCHAR(45) NOT NULL,
  `APELLIDO2_SOLICITANTE` VARCHAR(45) NOT NULL,
  `DISTRITO_SOLICITANTE` VARCHAR(45) NOT NULL,
  `BARRIO_SOLICITANTE` VARCHAR(45) NOT NULL,
  `DIRECCION_SOLICITANTE` VARCHAR(45) NOT NULL,
  `TELEFONO_HABITACION` VARCHAR(45) NOT NULL,
  `TELEFONO_CELULAR` VARCHAR(45) NOT NULL,
  `MOTIVO_AYUDA` VARCHAR(140) NOT NULL,
  `ESTADO_SOLICITUD` VARCHAR(45) NOT NULL,
  `FECHA_REALIZADA` DATETIME NOT NULL,
  PRIMARY KEY (`ID_AYUDA_TEMPORAL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sigcd`.`t_beca_municipal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sigcd`.`t_beca_municipal` (
  `ID_BECA_MUNICIPAL` INT NOT NULL,
  `CEDULA_BENEFICIADO` VARCHAR(45) NOT NULL,
  `NOMBRE_BENEFICIADO` VARCHAR(45) NOT NULL,
  `APELLIDO1_BENEFICIADO` VARCHAR(45) NOT NULL,
  `APELLIDO2_BENEFICIADO` VARCHAR(45) NOT NULL,
  `DISTRITO_BENEFICIADO` VARCHAR(45) NOT NULL,
  `BARRIO_BENEFICIADO` VARCHAR(45) NOT NULL,
  `DIRECCION_BENEFICIADO` VARCHAR(45) NOT NULL,
  `TELEFONO_HABITACION` VARCHAR(45) NOT NULL,
  `TELEFONO_CELULAR` VARCHAR(45) NOT NULL,
  `FECHA_NACIMIENTO` DATE NOT NULL,
  `EDAD_BENEFICIADO` INT NOT NULL,
  `GRADO_CURSANDO` VARCHAR(45) NOT NULL,
  `CEDULA_MADRE` VARCHAR(45) NOT NULL,
  `NOMBRE_MADRE` VARCHAR(45) NOT NULL,
  `APELLIDO1_MADRE` VARCHAR(45) NOT NULL,
  `APELLIDO2_MADRE` VARCHAR(45) NOT NULL,
  `CEDULA_PADRE` VARCHAR(45) NOT NULL,
  `APELLIDO1_PADRE` VARCHAR(45) NOT NULL,
  `APELLIDO2_PADRE` VARCHAR(45) NOT NULL,
  `FECHA_REALIZADA` DATETIME NOT NULL,
  PRIMARY KEY (`ID_BECA_MUNICIPAL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
